################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=DP-4,preferred,0x512, 1.6666, transform, 0
monitor=DP-5,preferred,2560x0, 1.6666, transform, 3
